import type { Alumni, PortalState } from "./types";

/** Fixed clock so server and browser render the same dates. 5 Oct 2026, 08:00 UTC. */
export const NOW = Date.UTC(2026, 9, 5, 8, 0, 0);
const DAY = 24 * 60 * 60 * 1000;

export const DEMO_USER = {
  id: "user_meera",
  name: "Meera Iyer",
  email: "meera.iyer@sample.invalid",
  image: null as string | null,
};

const ME = DEMO_USER.email;

/**
 * Sample members for the standalone preview.
 *
 * These are placeholders, the same way the feed seed describes them: addresses
 * sit on `sample.invalid`, which cannot receive mail. They are not college records.
 */
function person(row: Partial<Alumni> & Pick<Alumni, "_id" | "name" | "email" | "batch" | "department">): Alumni {
  const [first, ...rest] = row.name.split(" ");
  return {
    phone: "",
    firstName: first ?? row.name,
    lastName: rest.join(" "),
    designation: "",
    company: "",
    region: "Chennai",
    location: "Chennai, Tamil Nadu, India",
    locationLat: 13.0827,
    locationLng: 80.2707,
    locationConsent: true,
    locationUpdatedAt: NOW - 2 * DAY,
    locationSource: "manual",
    address: "",
    companyDomain: "",
    workLocation: "Chennai",
    skills: [],
    industries: [],
    bio: "Sample member for the standalone preview.",
    avatarUrl: null,
    verified: true,
    featured: false,
    openToMentor: false,
    mentorTopics: [],
    hiddenFields: [],
    sharedFields: [],
    joinedAt: NOW - 40 * DAY,
    ...row,
  };
}

export function createState(): PortalState {
  const alumni: Alumni[] = [
    person({
      _id: "alumni_meera",
      name: "Meera Iyer",
      email: ME,
      phone: "9840011122",
      batch: 2021,
      department: "CSE",
      designation: "Platform Engineer",
      company: "Zoho",
      companyDomain: "zoho.com",
      region: "Chennai",
      location: "Chennai, Tamil Nadu, India",
      locationLat: 13.0827,
      locationLng: 80.2707,
      workLocation: "Chennai",
      skills: ["TypeScript", "Distributed systems"],
      industries: ["Software"],
      bio: "Sample profile for the signed-in preview. CSE, batch of 2021, building internal platforms at Zoho.",
      verified: true,
      featured: true,
      openToMentor: true,
      mentorTopics: ["First job", "Switching to product"],
      sharedFields: ["email"],
      joinedAt: NOW - 80 * DAY,
    }),
    person({
      _id: "alumni_meenakshi",
      name: "Meenakshi Sundaram",
      email: "meenakshi.s@sample.invalid",
      batch: 2021,
      department: "CSE",
      designation: "Software Engineer",
      company: "Zoho",
      region: "Chennai",
      bio: "Sample member. Still measures every codebase against the final-year project.",
      featured: true,
      openToMentor: true,
      mentorTopics: ["First job"],
    }),
    person({
      _id: "alumni_arun",
      name: "Arunkumar Rajendran",
      email: "arun.k@sample.invalid",
      batch: 2020,
      department: "MECH",
      designation: "Design Engineer",
      company: "Ashok Leyland",
      region: "Coimbatore",
      location: "Coimbatore, Tamil Nadu, India",
      locationLat: 11.0168,
      locationLng: 76.9558,
      workLocation: "Hosur",
      verified: false,
      bio: "Sample member. Hiring design engineers and would rather they came from RIT.",
    }),
    person({
      _id: "alumni_divya",
      name: "Divya Ramanathan",
      email: "divya.r@sample.invalid",
      batch: 2022,
      department: "IT",
      designation: "Product Analyst",
      company: "Freshworks",
      region: "Chennai",
      featured: true,
      openToMentor: true,
      mentorTopics: ["Choosing between offers", "Product"],
      bio: "Sample member. Happy to talk through a first offer with anyone from IT.",
    }),
    person({
      _id: "alumni_karthik",
      name: "Karthikeyan Velu",
      email: "karthik.v@sample.invalid",
      batch: 2020,
      department: "ECE",
      designation: "Founder",
      company: "Kovai Systems",
      region: "Coimbatore",
      location: "Coimbatore, Tamil Nadu, India",
      locationLat: 11.0168,
      locationLng: 76.9558,
      workLocation: "Coimbatore",
      featured: true,
      openToMentor: true,
      mentorTopics: ["Starting a company"],
      bio: "Sample founder. Runs Kovai Systems and helps upcoming founders with their first customers.",
    }),
    person({
      _id: "alumni_priya",
      name: "Priyadharshini Nagarajan",
      email: "priya.n@sample.invalid",
      batch: 2023,
      department: "AIDS",
      designation: "Data Scientist",
      company: "Tiger Analytics",
      region: "Bengaluru",
      location: "Bengaluru, Karnataka, India",
      locationLat: 12.9716,
      locationLng: 77.5946,
      workLocation: "Bengaluru",
      bio: "Sample member. Went back to campus last month and found the library had doubled.",
    }),
    person({
      _id: "alumni_rahul",
      name: "Rahul Krishnan",
      email: "rahul.k@sample.invalid",
      batch: 2019,
      department: "EEE",
      designation: "Project Engineer",
      company: "Larsen & Toubro",
      region: "Hyderabad",
      location: "Hyderabad, Telangana, India",
      locationLat: 17.385,
      locationLng: 78.4867,
      workLocation: "Hyderabad",
      openToMentor: true,
      mentorTopics: ["Core engineering"],
      bio: "Sample member. Works on substation projects and mentors EEE students before placements.",
    }),
    person({
      _id: "alumni_anitha",
      name: "Anitha Selvam",
      email: "anitha.s@sample.invalid",
      batch: 2018,
      department: "CIVIL",
      designation: "Site Engineer",
      company: "Ramco Cements",
      region: "Madurai",
      location: "Madurai, Tamil Nadu, India",
      locationLat: 9.9252,
      locationLng: 78.1198,
      workLocation: "Madurai",
      bio: "Sample member. On sites around Virudhunagar and glad the association still meets in Rajapalayam.",
    }),
  ];

  const events = [
    {
      _id: "event_sangamam",
      title: "Sangamam 2026",
      slug: "sangamam-2026",
      kind: "reunion",
      summary: "The annual reunion on campus. Batches from 2017 onward, one evening, one hall.",
      description:
        "Sangamam is the association's reunion. Register once, bring up to two guests, and the office will remind you the week before. This is sample copy for the standalone preview.",
      startsAt: NOW + 21 * DAY,
      endsAt: NOW + 21 * DAY + 5 * 60 * 60 * 1000,
      mode: "onsite",
      venue: "RIT campus, Rajapalayam",
      capacity: 240,
      ticketPriceInr: 0,
      coverUrl: "/campus-1.jpg",
      published: true,
    },
    {
      _id: "event_clinic",
      title: "Founder clinic",
      slug: "founder-clinic",
      kind: "webinar",
      summary: "An hour with RACE on the first customers, the licence, and what to ask an alumnus for.",
      description:
        "A short clinic for anyone who has marked a venture as upcoming. Established founders take questions. Sample event for the standalone preview.",
      startsAt: NOW + 8 * DAY,
      endsAt: NOW + 8 * DAY + 60 * 60 * 1000,
      mode: "online",
      venue: "Online",
      capacity: 80,
      ticketPriceInr: 0,
      coverUrl: "/campus-3.jpg",
      published: true,
    },
    {
      _id: "event_sports",
      title: "Alumni sports league",
      slug: "sports-league-2026",
      kind: "sports",
      summary: "Cricket and throwball on the campus grounds. Last season's fixture, kept so the past list is not empty.",
      description: "Sample recap of a past fixture. The scores were not recorded here.",
      startsAt: NOW - 45 * DAY,
      endsAt: NOW - 45 * DAY + 6 * 60 * 60 * 1000,
      mode: "onsite",
      venue: "RIT grounds, Rajapalayam",
      capacity: 120,
      ticketPriceInr: 0,
      coverUrl: "/campus-5.jpg",
      published: true,
    },
  ];

  const stories = [
    {
      _id: "story_library",
      title: "The library has doubled",
      slug: "the-library-has-doubled",
      category: "recap",
      excerpt: "A visit back to Rajapalayam, and what the campus looks like to someone who left in 2023.",
      body: "Sample story for the standalone preview.\n\nPriya went back to campus and found the library had doubled. The photographs from that visit are in the gallery. Nothing here is a college record.",
      authorName: "Priyadharshini Nagarajan",
      authorBatch: 2023,
      coverUrl: "/campus-4.jpg",
      downloadUrl: null,
      featured: true,
      publishedAt: NOW - 6 * DAY,
    },
    {
      _id: "story_first_job",
      title: "Ask to meet the manager",
      slug: "ask-to-meet-the-manager",
      category: "success",
      excerpt: "The first job matters less than the first manager. A note for anyone weighing two offers.",
      body: "Sample story for the standalone preview.\n\nIf you are in your final year and weighing two offers, ask to speak to whoever you would report to. Any company worth joining will arrange it.",
      authorName: "Divya Ramanathan",
      authorBatch: 2022,
      coverUrl: "/campus-2.jpg",
      downloadUrl: null,
      featured: true,
      publishedAt: NOW - 12 * DAY,
    },
    {
      _id: "story_newsletter",
      title: "RITAA notes — October",
      slug: "ritaa-notes-october",
      category: "newsletter",
      excerpt: "Sangamam dates, the founder clinic, and where the scholarship fund stands.",
      body: "Sample newsletter for the standalone preview. Sangamam is on the calendar, the founder clinic is online, and the scholarship fund is open.",
      authorName: "RITAA",
      authorBatch: null,
      coverUrl: "/campus-6.jpg",
      downloadUrl: null,
      featured: false,
      publishedAt: NOW - 3 * DAY,
    },
    {
      _id: "story_achievement",
      title: "A design seat filled from the directory",
      slug: "a-design-seat-filled",
      category: "achievement",
      excerpt: "One referral, one role. The career hub is how the association would rather hiring worked.",
      body: "Sample story for the standalone preview. A mechanical role was posted by an alumnus who offered to walk the CV in. That is the shape of the career hub.",
      authorName: "Arunkumar Rajendran",
      authorBatch: 2020,
      coverUrl: "/campus-3.jpg",
      downloadUrl: null,
      featured: true,
      publishedAt: NOW - 18 * DAY,
    },
  ];

  const campaigns = [
    {
      _id: "campaign_scholarships",
      title: "Merit scholarships",
      slug: "merit-scholarships",
      cause: "Scholarships",
      batch: undefined as number | undefined,
      summary: "Fees for students the department has already named. Every rupee is listed against a line.",
      goalInr: 500000,
      raisedInr: 185000,
      donorCount: 4,
      coverUrl: "/campus-2.jpg",
      allocations: [
        { label: "Tuition support", amountInr: 80000 },
        { label: "Hostel", amountInr: 25000 },
      ],
      active: true,
      closesAt: NOW + 60 * DAY,
    },
    {
      _id: "campaign_lab",
      title: "CSE lab refresh",
      slug: "cse-lab-refresh",
      cause: "Campus",
      batch: 2021,
      summary: "A batch fund for the lab the 2021 cohort actually used.",
      goalInr: 250000,
      raisedInr: 60000,
      donorCount: 2,
      coverUrl: "/campus-6.jpg",
      allocations: [{ label: "Workstations", amountInr: 40000 }],
      active: true,
      closesAt: NOW + 90 * DAY,
    },
  ];

  const donations = [
    {
      _id: "gift_1",
      campaignId: "campaign_scholarships",
      donorName: "Meera Iyer",
      batch: 2021,
      amountInr: 25000,
      method: "upi",
      anonymous: false,
      message: "For whoever needs the hostel line this year.",
      createdAt: NOW - 10 * DAY,
    },
    {
      _id: "gift_2",
      campaignId: "campaign_scholarships",
      donorName: "Anonymous donor",
      batch: 2020,
      amountInr: 50000,
      method: "netbanking",
      anonymous: true,
      message: null,
      createdAt: NOW - 20 * DAY,
    },
    {
      _id: "gift_3",
      campaignId: "campaign_scholarships",
      donorName: "Divya Ramanathan",
      batch: 2022,
      amountInr: 10000,
      method: "upi",
      anonymous: false,
      message: null,
      createdAt: NOW - 4 * DAY,
    },
    {
      _id: "gift_4",
      campaignId: "campaign_lab",
      donorName: "Meenakshi Sundaram",
      batch: 2021,
      amountInr: 15000,
      method: "card",
      anonymous: false,
      message: "The lab we lived in.",
      createdAt: NOW - 8 * DAY,
    },
  ];

  const ventures = [
    {
      _id: "venture_kovai",
      founderName: "Karthikeyan Velu",
      founderEmail: "karthik.v@sample.invalid",
      founderBatch: 2020,
      age: 28,
      contact: "",
      businessName: "Kovai Systems",
      category: "Software",
      website: "https://example.com",
      description:
        "Sample venture. A small product studio in Coimbatore. The founder offers help with a first set of customers.",
      productImageUrls: ["/campus-3.jpg"],
      stage: "established",
      lookingFor: [],
      offersHelp: ["First customers", "Pricing"],
      location: "Coimbatore",
      approved: true,
      createdAt: NOW - 30 * DAY,
    },
    {
      _id: "venture_kiln",
      founderName: "Anitha Selvam",
      founderEmail: "anitha.s@sample.invalid",
      founderBatch: 2018,
      businessName: "Kiln & Co",
      category: "Manufacturing",
      website: null,
      description:
        "Sample idea. A small materials workshop that needs a read on which certification body actually signs off a retrofit kit.",
      productImageUrls: [],
      stage: "upcoming",
      lookingFor: ["Certification", "First customers"],
      offersHelp: [],
      location: "Rajapalayam",
      approved: true,
      createdAt: NOW - 9 * DAY,
    },
    {
      _id: "venture_pending",
      founderName: "Rahul Krishnan",
      founderEmail: "rahul.k@sample.invalid",
      founderBatch: 2019,
      businessName: "Grid Notes",
      category: "Energy",
      website: null,
      description: "Sample submission waiting on the coordinator. Not visible on the public feed.",
      productImageUrls: [],
      stage: "upcoming",
      lookingFor: ["Mentorship"],
      offersHelp: [],
      location: "Hyderabad",
      approved: false,
      createdAt: NOW - 2 * DAY,
    },
  ];

  const jobs = [
    {
      _id: "job_design",
      title: "Design Engineer",
      company: "Ashok Leyland",
      location: "Hosur",
      type: "full-time",
      experience: "1–3 years",
      description:
        "Sample opening. Mechanical or production, 2019 batch onwards. The poster will walk a CV to the hiring manager.",
      skills: ["CAD", "GD&T"],
      applyUrl: "https://example.com/jobs/design",
      postedByName: "Arunkumar Rajendran",
      postedByEmail: "arun.k@sample.invalid",
      postedByBatch: 2020,
      referralOffered: true,
      active: true,
      createdAt: NOW - 5 * DAY,
    },
    {
      _id: "job_analyst",
      title: "Product Analyst intern",
      company: "Freshworks",
      location: "Chennai",
      type: "internship",
      experience: "Final year",
      description: "Sample internship. A summer with the product team, posted by an alumnus who can refer.",
      skills: ["SQL", "Writing"],
      applyUrl: null,
      postedByName: "Divya Ramanathan",
      postedByEmail: "divya.r@sample.invalid",
      postedByBatch: 2022,
      referralOffered: true,
      active: true,
      createdAt: NOW - 2 * DAY,
    },
  ];

  const communities = [
    {
      _id: "community_cse",
      name: "CSE, batch of 2021",
      slug: "cse-2021",
      tagline: "The people who sat in the same lab.",
      description: "Sample community for the 2021 computer science cohort. Open to anyone from that batch.",
      visibility: "open",
      createdByEmail: ME,
      scopeBatch: 2021,
      scopeDepartment: "CSE",
      memberCount: 2,
      postCount: 1,
      archived: false,
      createdAt: NOW - 50 * DAY,
      status: "approved",
    },
    {
      _id: "community_founders",
      name: "RACE founders",
      slug: "race-founders",
      tagline: "Established and upcoming, in one room.",
      description: "Sample community. Joining asks a short note so the room stays about the work.",
      visibility: "approval",
      createdByEmail: "karthik.v@sample.invalid",
      memberCount: 2,
      postCount: 0,
      archived: false,
      createdAt: NOW - 20 * DAY,
      status: "approved",
    },
    {
      _id: "community_pending",
      name: "Madurai chapter",
      slug: "madurai-chapter",
      tagline: "Anyone posted in Madurai.",
      description: "Sample request waiting on the association.",
      visibility: "open",
      createdByEmail: "anitha.s@sample.invalid",
      memberCount: 1,
      postCount: 0,
      archived: false,
      createdAt: NOW - 1 * DAY,
      status: "pending",
    },
  ];

  const questions = [
    {
      _id: "q_verify",
      scope: "verification",
      prompt: "Which lab did your batch use for the final-year project?",
      kind: "text",
      options: [],
      required: false,
      order: 0,
      active: true,
      createdByEmail: ME,
      createdAt: NOW - 15 * DAY,
    },
    {
      _id: "q_profile",
      scope: "profile",
      prompt: "What should a junior from your department ask you?",
      kind: "longText",
      options: [],
      required: false,
      order: 0,
      active: true,
      createdByEmail: ME,
      createdAt: NOW - 15 * DAY,
    },
    {
      _id: "q_poll",
      scope: "poll",
      postId: "post_poll",
      prompt: "Which month suits most people for the next reunion?",
      kind: "choice",
      options: ["January", "April", "August", "December"],
      required: true,
      order: 0,
      active: true,
      createdByEmail: "karthik.v@sample.invalid",
      createdAt: NOW - 7 * DAY,
    },
    {
      _id: "q_join",
      scope: "communityJoin",
      communityId: "community_founders",
      prompt: "What are you building, in one line?",
      kind: "text",
      options: [],
      required: true,
      order: 0,
      active: true,
      createdByEmail: "karthik.v@sample.invalid",
      createdAt: NOW - 20 * DAY,
    },
  ];

  const programmes = [
    "B.Tech — Artificial Intelligence and Data Science",
    "B.E — Civil Engineering",
    "B.Tech — Computer Science and Business Systems",
    "B.E — Computer Science and Engineering",
    "M.E — Computer Science and Engineering",
    "B.E — Computer Science and Engineering (AIML)",
    "B.E — Computer Science and Engineering (Cyber Security)",
    "B.E — Electrical and Electronics Engineering",
    "B.E — Electronics and Communication Engineering",
    "B.Tech — Information Technology",
    "B.E — Mechanical Engineering",
  ];

  const fieldSeeds: Array<{
    key: string;
    label: string;
    help?: string;
    kind: string;
    options: string[];
    required: boolean;
    locked: boolean;
  }> = [
    { key: "firstName", label: "First name", kind: "text", options: [], required: true, locked: true },
    { key: "lastName", label: "Last name", kind: "text", options: [], required: true, locked: true },
    {
      key: "email",
      label: "Email",
      help: "Confirmed by the preview session, so it cannot be edited here.",
      kind: "email",
      options: [],
      required: true,
      locked: true,
    },
    { key: "phone", label: "Phone number", kind: "phone", options: [], required: true, locked: false },
    { key: "location", label: "Current location", kind: "location", options: [], required: false, locked: false },
    { key: "address", label: "Address", kind: "longText", options: [], required: false, locked: false },
    {
      key: "batch",
      label: "Batch",
      kind: "select",
      options: ["2024-2028", "2023-2027", "2022-2026", "2021-2025", "2020-2024", "2019-2023", "2018-2022"],
      required: true,
      locked: true,
    },
    { key: "department", label: "Programme", kind: "select", options: programmes, required: true, locked: false },
    { key: "company", label: "Current company", kind: "company", options: [], required: false, locked: false },
    { key: "workLocation", label: "Current working place", kind: "text", options: [], required: false, locked: false },
    { key: "designation", label: "Position", kind: "position", options: [], required: false, locked: false },
  ];

  return {
    alumni,
    events,
    rsvps: [
      {
        _id: "rsvp_1",
        eventId: "event_sangamam",
        name: "Meenakshi Sundaram",
        email: "meenakshi.s@sample.invalid",
        batch: 2021,
        guests: 1,
        status: "going",
        createdAt: NOW - 3 * DAY,
      },
      {
        _id: "rsvp_2",
        eventId: "event_clinic",
        name: "Meera Iyer",
        email: ME,
        batch: 2021,
        guests: 0,
        status: "going",
        createdAt: NOW - 1 * DAY,
      },
    ],
    reminders: [],
    stories,
    albums: [
      {
        _id: "album_1",
        title: "Convocation — Rajapalayam campus",
        year: 2025,
        eventName: "Convocation",
        coverUrl: "/campus-1.jpg",
        imageUrls: ["/campus-1.jpg", "/campus-2.jpg", "/campus-3.jpg"],
      },
      {
        _id: "album_2",
        title: "Degree day — graduating cohort",
        year: 2025,
        eventName: "Convocation",
        coverUrl: "/campus-4.jpg",
        imageUrls: ["/campus-4.jpg", "/campus-5.jpg", "/campus-6.jpg"],
      },
    ],
    campaigns,
    donations,
    ventures,
    jobs,
    connections: [
      {
        _id: "conn_meera_meenakshi",
        requesterEmail: ME,
        recipientEmail: "meenakshi.s@sample.invalid",
        status: "accepted",
        note: "Same lab, same batch.",
        createdAt: NOW - 20 * DAY,
        respondedAt: NOW - 19 * DAY,
      },
      {
        _id: "conn_arun_meera",
        requesterEmail: "arun.k@sample.invalid",
        recipientEmail: ME,
        status: "pending",
        note: "Looking for someone in product who can look at a design-engineer JD.",
        createdAt: NOW - 2 * DAY,
      },
      {
        _id: "conn_meera_divya",
        requesterEmail: ME,
        recipientEmail: "divya.r@sample.invalid",
        status: "pending",
        note: "Would like to compare notes on the analyst intern role.",
        createdAt: NOW - 1 * DAY,
      },
      {
        _id: "conn_meenakshi_karthik",
        requesterEmail: "meenakshi.s@sample.invalid",
        recipientEmail: "karthik.v@sample.invalid",
        status: "accepted",
        createdAt: NOW - 15 * DAY,
        respondedAt: NOW - 14 * DAY,
      },
    ],
    conversations: [
      {
        _id: "thread_1",
        participantA: "meenakshi.s@sample.invalid",
        participantB: ME,
        lastMessageAt: NOW - 6 * 60 * 60 * 1000,
        lastMessagePreview: "I will be at Sangamam. Save me a seat.",
        lastSenderEmail: "meenakshi.s@sample.invalid",
        createdAt: NOW - 4 * DAY,
      },
    ],
    messages: [
      {
        _id: "msg_1",
        conversationId: "thread_1",
        senderEmail: ME,
        body: "Are you coming to Sangamam?",
        createdAt: NOW - 5 * 60 * 60 * 1000,
        readAt: NOW - 4 * 60 * 60 * 1000,
      },
      {
        _id: "msg_2",
        conversationId: "thread_1",
        senderEmail: "meenakshi.s@sample.invalid",
        body: "I will be at Sangamam. Save me a seat.",
        createdAt: NOW - 6 * 60 * 60 * 1000,
      },
    ],
    communities,
    communityMembers: [
      {
        _id: "cm_1",
        communityId: "community_cse",
        email: ME,
        role: "admin",
        status: "active",
        createdAt: NOW - 50 * DAY,
        decidedAt: NOW - 50 * DAY,
      },
      {
        _id: "cm_2",
        communityId: "community_cse",
        email: "meenakshi.s@sample.invalid",
        role: "member",
        status: "active",
        createdAt: NOW - 40 * DAY,
        decidedAt: NOW - 40 * DAY,
      },
      {
        _id: "cm_3",
        communityId: "community_founders",
        email: "karthik.v@sample.invalid",
        role: "admin",
        status: "active",
        createdAt: NOW - 20 * DAY,
      },
      {
        _id: "cm_4",
        communityId: "community_founders",
        email: ME,
        role: "member",
        status: "active",
        createdAt: NOW - 12 * DAY,
        decidedAt: NOW - 11 * DAY,
      },
      {
        _id: "cm_5",
        communityId: "community_founders",
        email: "rahul.k@sample.invalid",
        role: "member",
        status: "pending",
        note: "Working on a grid-monitoring note and want the room.",
        createdAt: NOW - 1 * DAY,
      },
      {
        _id: "cm_6",
        communityId: "community_pending",
        email: "anitha.s@sample.invalid",
        role: "admin",
        status: "active",
        createdAt: NOW - 1 * DAY,
      },
    ],
    posts: [
      {
        _id: "post_lab",
        authorEmail: "meenakshi.s@sample.invalid",
        body: "Four years since we walked out of the CSE block and I still measure every codebase against the one we wrote for our final year project.\n\nPut your details in if you have not yet.",
        kind: "text",
        imageUrls: [],
        videoUrls: [],
        likeCount: 2,
        commentCount: 1,
        shareCount: 0,
        hidden: false,
        createdAt: NOW - 14 * 60 * 60 * 1000,
      },
      {
        _id: "post_hiring",
        authorEmail: "arun.k@sample.invalid",
        body: "We are hiring two design engineers, and I would rather they came from here.\n\nMechanical or production, 2019 batch onwards, Hosur or Chennai. Connect with me and send your CV through the portal.",
        kind: "text",
        imageUrls: [],
        videoUrls: [],
        likeCount: 1,
        commentCount: 0,
        shareCount: 0,
        hidden: false,
        createdAt: NOW - 11 * 60 * 60 * 1000,
      },
      {
        _id: "post_poll",
        authorEmail: "karthik.v@sample.invalid",
        body: "Which month suits most people for the next reunion?\n\nWe would rather ask than guess. One vote each.",
        kind: "poll",
        imageUrls: [],
        videoUrls: [],
        likeCount: 0,
        commentCount: 0,
        shareCount: 0,
        hidden: false,
        createdAt: NOW - 8 * 60 * 60 * 1000,
      },
      {
        _id: "post_campus",
        authorEmail: "priya.n@sample.invalid",
        body: "Went back to campus last month for the first time since graduating and the library has doubled.",
        kind: "text",
        imageUrls: ["/campus-4.jpg", "/campus-6.jpg"],
        videoUrls: [],
        likeCount: 3,
        commentCount: 0,
        shareCount: 0,
        hidden: false,
        createdAt: NOW - 5 * 60 * 60 * 1000,
      },
      {
        _id: "post_community",
        authorEmail: ME,
        communityId: "community_cse",
        body: "If anyone from 2021 CSE is in Chennai the week of Sangamam, say so here and we can share a car down.",
        kind: "text",
        imageUrls: [],
        videoUrls: [],
        likeCount: 1,
        commentCount: 0,
        shareCount: 0,
        hidden: false,
        createdAt: NOW - 3 * 60 * 60 * 1000,
      },
    ],
    comments: [
      {
        _id: "comment_1",
        postId: "post_lab",
        authorEmail: ME,
        body: "That project is still the one I explain in interviews.",
        hidden: false,
        createdAt: NOW - 10 * 60 * 60 * 1000,
      },
    ],
    likes: [
      { _id: "like_1", postId: "post_lab", email: ME, createdAt: NOW - 12 * 60 * 60 * 1000 },
      { _id: "like_2", postId: "post_lab", email: "divya.r@sample.invalid", createdAt: NOW - 11 * 60 * 60 * 1000 },
      { _id: "like_3", postId: "post_campus", email: ME, createdAt: NOW - 4 * 60 * 60 * 1000 },
    ],
    questions,
    answers: [
      { _id: "ans_1", questionId: "q_poll", email: ME, scope: "poll", postId: "post_poll", answer: "August", createdAt: NOW - 2 * 60 * 60 * 1000 },
      { _id: "ans_2", questionId: "q_poll", email: "meenakshi.s@sample.invalid", scope: "poll", postId: "post_poll", answer: "August", createdAt: NOW - 90 * 60 * 1000 },
      { _id: "ans_3", questionId: "q_poll", email: "divya.r@sample.invalid", scope: "poll", postId: "post_poll", answer: "April", createdAt: NOW - 60 * 60 * 1000 },
      { _id: "ans_4", questionId: "q_profile", email: ME, scope: "profile", answer: "How to tell two offers apart when both look fine on paper.", createdAt: NOW - 20 * DAY },
    ],
    profileFields: fieldSeeds.map((field, order) => ({
      _id: `field_${field.key}`,
      ...field,
      help: field.help ?? null,
      active: true,
      order,
      updatedAt: NOW - 30 * DAY,
    })),
    mentorship: [
      {
        _id: "mentor_req_1",
        mentorId: "alumni_meera",
        seekerName: "A student from IT",
        seekerEmail: "student.it@sample.invalid",
        seekerKind: "student",
        topic: "First job",
        message: "I have two offers and I do not know how to choose. Can we talk for twenty minutes?",
        preferredSlot: "Saturday morning",
        status: "requested",
        createdAt: NOW - 2 * DAY,
      },
      {
        _id: "mentor_req_2",
        mentorId: "alumni_divya",
        seekerName: "Meera Iyer",
        seekerEmail: ME,
        seekerKind: "alumnus",
        topic: "Product",
        message: "I want a read on moving from platform work into product.",
        preferredSlot: "Any weekday evening",
        status: "completed",
        feedbackRating: 5,
        feedbackNote: "Clear and specific.",
        createdAt: NOW - 25 * DAY,
      },
    ],
    verifications: [
      {
        _id: "ver_1",
        name: "Arunkumar Rajendran",
        email: "arun.k@sample.invalid",
        batch: 2020,
        department: "MECH",
        rollNumber: "953620114001",
        graduationYear: 2020,
        status: "pending",
        createdAt: NOW - 3 * DAY,
      },
    ],
    roles: [
      { email: ME, role: "admin" },
      { email: "karthik.v@sample.invalid", role: "entrepreneur" },
    ],
    students: [
      {
        _id: "student_1",
        slNo: 1,
        firstName: "Abinaya",
        middleName: "",
        lastName: "R",
        personalEmail: "abinaya.r@sample.invalid",
        secondaryEmail: "",
        phone: "9876543210",
        secondaryPhone: "",
        enrollmentNumber: "953622104001",
        degree: "B.E",
        departmentRaw: "Computer Science and Engineering",
        department: "CSE",
        permanentAddress: "Rajapalayam",
        designation: "",
        company: "",
        yearOfPassing: 2026,
        yearOfJoining: 2022,
        collegeEmail: "953622104001@ritrjpm.ac.in",
        fullName: "Abinaya R",
        searchText: "Abinaya R 953622104001 953622104001@ritrjpm.ac.in",
        importedAt: NOW - 10 * DAY,
        importedByEmail: ME,
        importBatchId: "batch_sample",
      },
    ],
    importBatches: [
      {
        _id: "import_sample",
        batchId: "batch_sample",
        fileName: "sample-roster.xlsx",
        sheetName: "CSE",
        uploadedByEmail: ME,
        createdAt: NOW - 10 * DAY,
        rowsSeen: 1,
        imported: 1,
        updated: 0,
        rejected: 0,
        dryRun: false,
      },
    ],
  };
}
